server:
  port: 8060

spring:
  application:
    name: b2b-gateway

management:
  security:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

zuul:
  ignoredServices: '*'
  routes:
    b2b-auth-service:
      path: /uaa/**
     serviceId: tensquare-search
    b2b-shop-service:
      path: /shop/**
      serviceId: tensquare-search
    b2b-order-service:
      path: /order/**
      serviceId: tensquare-search