server:
  port: 8060

management:
  security:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

zuul:
  ignoredServices: '*'
  routes:
    b2b-auth-service:
      path: /uaa/**
      stripPrefix: false
      sensitiveHeaders:
    b2b-shop-service:
      path: /shop/**
      sensitiveHeaders:
    b2b-order-service:
      path: /order/**
      sensitiveHeaders: