server:
  port: 8060

spring:
  application:
    name: b2b-gateway

management:
  security:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

zuul:
  routes:
    b2b-auth-service:
      path: /uaa/**
      serviceId: b2b-auth-service
    b2b-shop-service:
      path: /shop/**
      serviceId: b2b-shop-service
    b2b-order-service:
      path: /order/**
      serviceId: b2b-order-service
